apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab
data:
  config.toml: |
    concurrent = 4

    [[runners]]
      name = "Kubernetes Runner"
      url = "https://gitlab.tiir.ovh/"
      token = "bc98d9394b7501ae23a0a0006a468b"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab"
        image = "busybox"
    [[runners.kubernetes.volumes.host_path]]
      name = "hostpath-1"
      mount_path = "/var/run/docker.sock"
      read_only = false
      host_path = "/var/run/docker.sock"
