kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitlab
  name: gitlab-admin
rules:
- apiGroups: [""] # The API group "" indicates the core API Group.
  resources: ["*"]
  verbs: ["*"]
