#!/bin/sh

# Set these paths appropriately

BIN="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/bin"
CMD="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/cmd"
LIB="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
