#!/bin/sh

# Set these paths appropriately

BIN="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/bin"
CMD="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/cmd"
LIB="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
