#!/bin/sh

# Set these paths appropriately

BIN="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/bin"
CMD="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/cmd"
LIB="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

