version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: article
    ports:
      - "5432:5432"
    volumes:
      - ./src:/project
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
