contest0: contest0.c
	gcc contest0.c -o contest0

equilibre: equilibre.c
	gcc equilibre.c -o equilibre

majorite: majorite.c
	gcc majorite.c -o majorite

equipe: equipe.c
	gcc equipe.c -o equipe

ligne_toit: ligne_toit.c
	gcc ligne_toit.c -o ligne_toit

labo: labo.c
	gcc labo.c -o labo

bouteilles: bouteilles.c
	gcc bouteilles.c -o bouteilles

plssc: plssc.c
	gcc plssc.c -o plssc

fusion_k_tab: fusion_k_tab.cpp
	g++ fusion_k_tab.cpp -o fusion_k_tab

clean:
	rm contest0 equilibre majorite equipe ligne_toit labo
