ex1: ex1.c
	gcc ex1.c -o ex1

ex1_2: ex1_2.c
	gcc ex1_2.c -o ex1_2

ex2: ex2.c
	gcc ex2.c -o ex2

ex3: ex3.c
	gcc ex3.c -o ex3

ex4: ex4.c
	gcc ex4.c -o ex4
	
display_stack: display_stack.c
	gcc display_stack.c -o display_stack

clean:
	rm ex1 || rm ex1_2 || rm ex2 || rm ex3 || rm ex4 || echo 'already clean'
