out1:
	as -a --gstabs -o out1.o out1.s
	ld -o out1 out1.o
	
out11:
	as -a --gstabs -o out1.o out1.s
	ld -o out1 out1.o
	
out2:
	as -a --gstabs -o out2.o out2.s
	ld -o out2 out2.o
	
out22:
	as -a --gstabs -o out2.o out2.s
	ld -o out2 out2.o
