#!/bin/sh

# Set these paths appropriately

BIN="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/bin"
CMD="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/cmd"
LIB="/home/m2ml/lakhdar/Documents/M2/BG/lib/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
