version: "3"

services:
  server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.server
      args:
        dummy: 1
    image: pje-tweeter-server:0.1.0
    ports:
      - "5000:5000"
  db:
    container_name: pje-tweeter-db
    image: mongo
    volumes:
      - ../data/db:/data/db
    ports:
      - "27017:27017"