ARD:
	mkdir -p bin/
	javac -cp src/ src/ard/TestARD.java -d bin/
	java -cp bin/ ard.TestARD
	
ARDlex:
	mkdir -p bin/
	javac -cp src/ src/Exe2/Main.java -d bin/
	java -cp bin/ Exe2.Main

clean:
	rm -rf bin
