version: "3"

services:
  front:
    hostname: frontend
    image: frontend:v1
    ports:
      - "80:80"
      - "443:443"
    #volumes:
      #- ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      #- ./config/fastcgi.conf:/etc/nginx/conf.d/fastcgi.conf
      #- ./config/proxy.conf:/etc/nginx/conf.d/proxy.conf
      #- ./config/mimes.types:/etc/nginx/conf.d/mimes.types
      #- ./frontend:/usr/share/nginx/html
    environment:
      - NGINX_HOST=changeme.com
      - NGINX_PORT=80
      - BACKEND_URL="http://localhost:8080"
