#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.org1.fly.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.fly.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7e341b0488d18b3262dfb0b10af6c4f1c37aa4c168b9342f317f8dc41db4d147_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.fly.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7e341b0488d18b3262dfb0b10af6c4f1c37aa4c168b9342f317f8dc41db4d147_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.fly.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  ca.org2.fly.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.fly.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/00ae5786b15c0b7cd7bf07bbf249c98acf4558c1467d07724a43c05bab553b28_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.fly.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/00ae5786b15c0b7cd7bf07bbf249c98acf4558c1467d07724a43c05bab553b28_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org2.fly.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    
  ca.org3.fly.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.fly.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e0b50bb98e63dfc52b1dee34cede962add5aa9f554a468ac0e5aa4d4f8d28499_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.fly.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e0b50bb98e63dfc52b1dee34cede962add5aa9f554a468ac0e5aa4d4f8d28499_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org3.fly.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel/ca_config/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg3

  orderer.fly.com:
    container_name: orderer.fly.com
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerOrg1/tls/ca.crt, /etc/hyperledger/crypto/peerOrg2/tls/ca.crt, /etc/hyperledger/crypto/peerOrg3/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/fly.com/orderers/orderer.fly.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/org1.fly.com/peers/peer0.org1.fly.com/:/etc/hyperledger/crypto/peerOrg1
        - ./channel/crypto-config/peerOrganizations/org2.fly.com/peers/peer0.org2.fly.com/:/etc/hyperledger/crypto/peerOrg2
        - ./channel/crypto-config/peerOrganizations/org3.fly.com/peers/peer0.org3.fly.com/:/etc/hyperledger/crypto/peerOrg3

  peer0.org1.fly.com:
    container_name: peer0.org1.fly.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.fly.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.fly.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.fly.com/peers/peer0.org1.fly.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.fly.com

  peer1.org1.fly.com:
    container_name: peer1.org1.fly.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.fly.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.fly.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.fly.com/peers/peer1.org1.fly.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.fly.com

  peer0.org2.fly.com:
    container_name: peer0.org2.fly.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.fly.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.fly.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.fly.com/peers/peer0.org2.fly.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.fly.com

  peer1.org2.fly.com:
    container_name: peer1.org2.fly.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.fly.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.fly.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org2.fly.com/peers/peer1.org2.fly.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.fly.com

  peer0.org3.fly.com:
      container_name: peer0.org3.fly.com
      extends:
        file:   base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=peer0.org3.fly.com
        - CORE_PEER_LOCALMSPID=Org3MSP
        - CORE_PEER_ADDRESS=peer0.org3.fly.com:7051
      ports:
        - 9051:7051
        - 9053:7053
      volumes:
          - ./channel/crypto-config/peerOrganizations/org3.fly.com/peers/peer0.org3.fly.com/:/etc/hyperledger/crypto/peer
      depends_on:
        - orderer.fly.com

  peer1.org3.fly.com:
      container_name: peer1.org3.fly.com
      extends:
        file:   base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=peer1.org3.fly.com
        - CORE_PEER_LOCALMSPID=Org3MSP
        - CORE_PEER_ADDRESS=peer1.org3.fly.com:7051
      ports:
        - 9056:7051
        - 9058:7053
      volumes:
          - ./channel/crypto-config/peerOrganizations/org3.fly.com/peers/peer1.org3.fly.com/:/etc/hyperledger/crypto/peer
      depends_on:
        - orderer.fly.com